# Generated by Django 3.2.12 on 2022-12-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
